# Generated by Django 4.1.5 on 2023-10-30 10:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='news_title', unique=True),
        ),
    ]
