# Generated by Django 4.1.5 on 2023-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_enquiry_alter_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
